from typing import Literal

GetMonitorFieldsItem = Literal[
    "attached",
    "attachedResults",
    "certNotBefore",
    "created",
    "cronSchedule",
    "disabledSpans",
    "effectiveUrl",
    "enabled",
    "expirationDate",
    "fullLog",
    "id",
    "interval",
    "lastIncident",
    "lastResult",
    "locations",
    "maintenance",
    "maintenanceSpans",
    "name",
    "openStat",
    "recheck",
    "settings",
    "since",
    "slaTarget",
    "spans",
    "state",
    "subscription",
    "tags",
    "type",
    "updated",
    "uptime",
    "url",
]

GET_MONITOR_FIELDS_ITEM_VALUES: set[GetMonitorFieldsItem] = {
    "attached",
    "attachedResults",
    "certNotBefore",
    "created",
    "cronSchedule",
    "disabledSpans",
    "effectiveUrl",
    "enabled",
    "expirationDate",
    "fullLog",
    "id",
    "interval",
    "lastIncident",
    "lastResult",
    "locations",
    "maintenance",
    "maintenanceSpans",
    "name",
    "openStat",
    "recheck",
    "settings",
    "since",
    "slaTarget",
    "spans",
    "state",
    "subscription",
    "tags",
    "type",
    "updated",
    "uptime",
    "url",
}


def check_get_monitor_fields_item(value: str) -> GetMonitorFieldsItem:
    if value in GET_MONITOR_FIELDS_ITEM_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {GET_MONITOR_FIELDS_ITEM_VALUES!r}")
